import { tierOrder, type CharacterDetail, type CharacterSummary, type TierGroup } from '@/entities/character/model/types/character';

// Variant naming and relative mock tiering were seeded from current Phantom Parade
// reroll/meta references checked on April 28, 2026. Base character art is from
// the official Jujutsu Kaisen site and stored locally in /public/characters.

type BaseCharacterKey =
  | 'gojo'
  | 'sukuna'
  | 'yuta'
  | 'toji'
  | 'mahito'
  | 'yuji'
  | 'megumi'
  | 'nobara'
  | 'nanami'
  | 'maki'
  | 'toge'
  | 'panda';

const baseCharacters = {
  gojo: {
    baseName: '고죠 사토루',
    image: '/characters/gojo.png',
    officialCategory: 'sorcerer',
  },
  sukuna: {
    baseName: '료멘 스쿠나',
    image: '/characters/sukuna.png',
    officialCategory: 'curse-side',
  },
  yuta: {
    baseName: '옷코츠 유타',
    image: '/characters/yuta.png',
    officialCategory: 'tokyo-school',
  },
  toji: {
    baseName: '후시구로 토우지',
    image: '/characters/toji.png',
    officialCategory: 'curse-side',
  },
  mahito: {
    baseName: '마히토',
    image: '/characters/mahito.png',
    officialCategory: 'curse-side',
  },
  yuji: {
    baseName: '이타도리 유지',
    image: '/characters/yuji.png',
    officialCategory: 'tokyo-school',
  },
  megumi: {
    baseName: '후시구로 메구미',
    image: '/characters/megumi.png',
    officialCategory: 'tokyo-school',
  },
  nobara: {
    baseName: '쿠기사키 노바라',
    image: '/characters/nobara.png',
    officialCategory: 'tokyo-school',
  },
  nanami: {
    baseName: '나나미 켄토',
    image: '/characters/nanami.png',
    officialCategory: 'sorcerer',
  },
  maki: {
    baseName: '젠인 마키',
    image: '/characters/maki.png',
    officialCategory: 'tokyo-school',
  },
  toge: {
    baseName: '이누마키 토게',
    image: '/characters/toge.png',
    officialCategory: 'tokyo-school',
  },
  panda: {
    baseName: '판다',
    image: '/characters/panda.png',
    officialCategory: 'tokyo-school',
  },
} as const;

interface UnitSeed {
  id: string;
  baseKey: BaseCharacterKey;
  variantName: string;
  title: string;
  trait: CharacterDetail['trait'];
  combatType: CharacterDetail['combatType'];
  role: CharacterDetail['role'];
  tier: CharacterDetail['tier'];
  rarity: CharacterDetail['rarity'];
  releaseType: string;
  description: string;
  passive: string;
  skills: CharacterDetail['skills'];
  ultimate: CharacterDetail['ultimate'];
}

const skill = (name: string, description: string, cooldown: string): CharacterDetail['skills'][number] => ({
  name,
  description,
  cooldown,
});

const buildVariantImage = (articleId: number) => `https://img.gamewith.jp/article/thumbnail/rectangle_l/${articleId}.png`;

const variantImageArticleIds: Record<string, number> = {
  'gojo-domain': 473281,
  'gojo-zero-point-two': 536682,
  'gojo-strongest': 426472,
  'gojo-ao': 450192,
  'gojo-hollow-purple': 434786,
  'gojo-limitless': 473281,
  'gojo-awakened': 497784,
  'yuji-zone': 473282,
  'yuji-maximum-output': 530925,
  'yuji-cursed-power': 444747,
  'yuji-lightfooted': 432466,
  'megumi-incomplete-domain': 431814,
  'megumi-inherited-technique': 426466,
  'megumi-bond': 466294,
  'megumi-rabbit': 517825,
  'nobara-steel': 426467,
  'nobara-compatible-nails': 439929,
  'nobara-drive-it-in': 464685,
  'nanami-suppression': 553100,
  'nanami-grade-one': 459862,
  'nanami-overtime': 449272,
  'nanami-ratio': 426473,
  'yuta-executioner': 551337,
  'yuta-queen': 524949,
  'yuta-lend-me-your-power': 429934,
  'toji-sorcerer-killer': 452079,
  'toji-incarnation': 514073,
  'mahito-soul': 532415,
  'mahito-death': 443429,
  'sukuna-fuga': 531833,
  'sukuna-true-jujutsu': 479749,
  'maki-rebellious': 426468,
  'maki-greatblade': 460220,
  'maki-early-morning': 491630,
  'toge-determination': 426469,
  'toge-crush': 463408,
  'toge-night-walk': 483330,
  'panda-mutant-corpse': 426470,
  'panda-helping-hand': 446417,
};

const createCharacter = (unit: UnitSeed): CharacterDetail => {
  const base = baseCharacters[unit.baseKey];
  const variantImageArticleId = variantImageArticleIds[unit.id];

  return {
    id: unit.id,
    name: `${unit.variantName} ${base.baseName}`,
    baseName: base.baseName,
    variantName: unit.variantName,
    title: unit.title,
    image: base.image,
    variantImage: variantImageArticleId ? buildVariantImage(variantImageArticleId) : undefined,
    trait: unit.trait,
    combatType: unit.combatType,
    role: unit.role,
    tier: unit.tier,
    rarity: unit.rarity,
    releaseType: unit.releaseType,
    officialCategory: base.officialCategory,
    description: unit.description,
    passive: unit.passive,
    skills: unit.skills,
    ultimate: unit.ultimate,
  };
};

const characterSeeds: UnitSeed[] = [
  {
    id: 'gojo-domain',
    baseKey: 'gojo',
    variantName: '무량공처',
    title: '광역 제압과 최고급 마무리 성능을 겸비한 핵심 한정 유닛',
    trait: 'illusion',
    combatType: 'hybrid',
    role: 'attacker',
    tier: 'SS',
    rarity: 'SSR',
    releaseType: '한정',
    description: '리세마라와 오토 메타에서 가장 먼저 거론되는 대표 고죠 변형입니다.',
    passive: '영역 전개 후 적 전체의 행동 효율을 크게 떨어뜨리고 자신의 생존력을 끌어올립니다.',
    skills: [
      skill('아오', '적 전체를 끌어당기며 술식 피해와 약화를 남깁니다.', '3턴'),
      skill('아카', '단일 적에게 폭발적인 타격을 주고 다음 필살기를 강화합니다.', '4턴'),
    ],
    ultimate: skill('무량공처', '전장 전체를 장악하는 대표 필살기로 구속과 광역 피해를 가합니다.', '궁극기'),
  },
  {
    id: 'gojo-zero-point-two',
    baseKey: 'gojo',
    variantName: '0.2초의 무량공처',
    title: '오토 성능과 광역 클리어 속도에서 최고 평가를 받는 최신 변형',
    trait: 'illusion',
    combatType: 'hybrid',
    role: 'attacker',
    tier: 'SS',
    rarity: 'SSR',
    releaseType: '한정',
    description: '2026년 초 기준 0.2초 고죠는 광역 스테이지와 오토에서 최상위권으로 평가됩니다.',
    passive: '전투 개시 직후부터 전체 공격 효율을 끌어올리고, 필살기 후 오토 루프가 강해집니다.',
    skills: [
      skill('초단위 개시', '전투 시작 템포를 앞당기며 광역 술식 피해를 가합니다.', '2턴'),
      skill('재압축한 영역', '적 전체의 받는 피해를 올리고 영역 계열 필살기를 보조합니다.', '4턴'),
    ],
    ultimate: skill('0.2초의 무량공처', '짧게 펼친 영역으로 적을 묶고 강한 전장 장악 효과를 남깁니다.', '궁극기'),
  },
  {
    id: 'gojo-strongest',
    baseKey: 'gojo',
    variantName: '최강',
    title: '높은 자기 버프와 필살기 계수로 정면 승부에 특화된 어태커',
    trait: 'shadow',
    combatType: 'hybrid',
    role: 'attacker',
    tier: 'SS',
    rarity: 'SSR',
    releaseType: '한정',
    description: '고전 고죠 계열 중에서도 순수 화력과 자기 강화가 강한 상위권 변형입니다.',
    passive: '턴이 지날수록 자기 버프가 겹쳐져 필살기 고점이 빠르게 상승합니다.',
    skills: [
      skill('최강의 감각', '자신의 술식과 회심 효율을 크게 끌어올립니다.', '3턴'),
      skill('붕괴 일격', '단일 적에게 강한 복합 피해를 가합니다.', '3턴'),
    ],
    ultimate: skill('최강의 붕락', '고계수 단일 피니시로 보스 체력을 크게 깎아내립니다.', '궁극기'),
  },
  {
    id: 'gojo-ao',
    baseKey: 'gojo',
    variantName: '아오',
    title: '범용성이 뛰어난 광역 술식 중심의 템포형 고죠',
    trait: 'shadow',
    combatType: 'cursed',
    role: 'attacker',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '한정',
    description: '유저가 가장 자주 찾는 변형 중 하나로, 카드명 자체로도 검색 수요가 높은 고죠 유닛입니다.',
    passive: '광역 술식 사용 후 자신의 턴 확보와 스킬 재활용 효율이 올라갑니다.',
    skills: [
      skill('술식 순전 청', '적 전체를 휩쓸며 술식 피해와 화력 저하를 부여합니다.', '2턴'),
      skill('중력 왜곡', '적의 진형을 흐트러뜨리고 추가 피해 조건을 만듭니다.', '3턴'),
    ],
    ultimate: skill('창공 압괴', '청의 압축 폭발로 광역 피해를 가하는 필살기입니다.', '궁극기'),
  },
  {
    id: 'gojo-hollow-purple',
    baseKey: 'gojo',
    variantName: '허식 자색',
    title: '단일 폭딜과 범위 마무리를 겸하는 자색 특화 유닛',
    trait: 'night',
    combatType: 'cursed',
    role: 'attacker',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '한정',
    description: '최대 화력 기준 상위권으로 묶이는 자색 고죠 계열의 대표 카드입니다.',
    passive: '자신의 공격 전 준비 단계가 끝나면 자색 계열 피해가 크게 상승합니다.',
    skills: [
      skill('청적 융합', '다음 자색 계열 스킬의 배율과 관통 성능을 강화합니다.', '3턴'),
      skill('폭심 유도', '단일 적을 압박하며 받는 피해 증가를 남깁니다.', '4턴'),
    ],
    ultimate: skill('허식 자색', '거대한 자색으로 직선 범위의 적을 관통하는 필살기입니다.', '궁극기'),
  },
  {
    id: 'gojo-limitless',
    baseKey: 'gojo',
    variantName: '무하한 주술',
    title: '무적 운영과 범용성으로 여전히 높은 평가를 받는 오리지널 축 유닛',
    trait: 'shadow',
    combatType: 'hybrid',
    role: 'support',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '일반',
    description: '리세마라 추천에서 오래 살아남은 이유가 분명한 범용 고죠입니다.',
    passive: '피격 직전 무하한을 전개해 적의 공격을 무효화하고 반격 조건을 얻습니다.',
    skills: [
      skill('무하한 전개', '짧은 시간 적의 공격을 무시하고 자신의 안정성을 확보합니다.', '3턴'),
      skill('아카 반전', '적 한 명을 강하게 날려보내고 디버프를 남깁니다.', '4턴'),
    ],
    ultimate: skill('무하한 붕락', '생존과 공격을 동시에 책임지는 범용 필살기입니다.', '궁극기'),
  },
  {
    id: 'gojo-awakened',
    baseKey: 'gojo',
    variantName: '각성',
    title: '자기 지원이 매우 강한 솔로 캐리형 각성 고죠',
    trait: 'action',
    combatType: 'hybrid',
    role: 'attacker',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '일반',
    description: '자기 지원 성능이 높아 솔로 캐리 성향이 강한 각성 고죠 변형입니다.',
    passive: '전투 중 한 번 각성 상태에 들어가면 자기 회복과 화력 상승을 동시에 얻습니다.',
    skills: [
      skill('각성 고양', '자신의 주력 효율과 회복력을 강화합니다.', '3턴'),
      skill('직격 압괴', '단일 적을 빠르게 압박하는 복합 공격입니다.', '3턴'),
    ],
    ultimate: skill('각성 일섬', '각성 상태에서 크게 강화되는 마무리 필살기입니다.', '궁극기'),
  },
  {
    id: 'yuji-zone',
    baseKey: 'yuji',
    variantName: '존',
    title: '2회 행동과 확정 흑섬으로 리세마라 상위권을 굳히는 핵심 딜러',
    trait: 'action',
    combatType: 'physical',
    role: 'attacker',
    tier: 'SS',
    rarity: 'SSR',
    releaseType: '한정',
    description: '최신 리세마라 페이지에서 항상 상단에 보이는 대표 유지 변형입니다.',
    passive: '존 상태에 진입하면 추가 행동과 회심 보정으로 턴 폭발력이 크게 올라갑니다.',
    skills: [
      skill('돌진 연격', '빠르게 파고들어 단일 대상에게 체술 피해를 누적합니다.', '2턴'),
      skill('흑섬 태세', '다음 공격의 회심률과 피해량을 동시에 끌어올립니다.', '3턴'),
    ],
    ultimate: skill('존 블랙 플래시', '존 상태에서 위력이 크게 상승하는 유지의 결정타입니다.', '궁극기'),
  },
  {
    id: 'yuji-maximum-output',
    baseKey: 'yuji',
    variantName: '최대 출력',
    title: '한 방 고점과 진입력에 초점을 둔 체술형 유지 변형',
    trait: 'night',
    combatType: 'physical',
    role: 'attacker',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '한정',
    description: '2nd 유지 계열로 묶어 볼 수 있는 공격형 변형으로, 한 턴 폭딜에 강합니다.',
    passive: '스택이 최대치에 도달하면 다음 필살기의 계수와 관통력이 크게 상승합니다.',
    skills: [
      skill('최대 출력 자세', '자신의 공격 스택을 빠르게 모읍니다.', '2턴'),
      skill('근거리 압박', '연속 타격으로 적을 몰아붙입니다.', '3턴'),
    ],
    ultimate: skill('최대 출력 흑섬', '한 점에 힘을 집중한 강력한 단일 필살기입니다.', '궁극기'),
  },
  {
    id: 'yuji-cursed-power',
    baseKey: 'yuji',
    variantName: '주력에 의한 일격',
    title: '단순하고 묵직한 화력으로 초중반을 이끄는 기본형 SSR 유지',
    trait: 'action',
    combatType: 'hybrid',
    role: 'attacker',
    tier: 'A',
    rarity: 'SSR',
    releaseType: '일반',
    description: '운영이 간단하고 투자 대비 체감이 좋은 유지의 기본 화력형 변형입니다.',
    passive: '연속 공격 후 자신의 체술 위력과 회심 피해가 차례로 상승합니다.',
    skills: [
      skill('주력 강타', '전방 적에게 묵직한 복합 피해를 줍니다.', '2턴'),
      skill('전진 압박', '행동 게이지를 회복하며 다음 타격을 준비합니다.', '3턴'),
    ],
    ultimate: skill('주력 일섬', '집중된 주력으로 단일 적을 때려눕히는 필살기입니다.', '궁극기'),
  },
  {
    id: 'yuji-lightfooted',
    baseKey: 'yuji',
    variantName: '경쾌한 신체',
    title: '회전율이 높은 경량형 유지 변형',
    trait: 'shadow',
    combatType: 'physical',
    role: 'breaker',
    tier: 'A',
    rarity: 'SSR',
    releaseType: '일반',
    description: '순발력과 게이지 회복을 살린 스피드형 유지 카드입니다.',
    passive: '회피나 속도 보정이 걸릴 때마다 브레이크 효율이 증가합니다.',
    skills: [
      skill('리듬 스텝', '빠르게 접근하며 브레이크 수치를 깎습니다.', '2턴'),
      skill('탄력 회복', '행동 게이지를 다시 당겨옵니다.', '3턴'),
    ],
    ultimate: skill('속공 흑섬', '빠르게 꽂아 넣는 기동형 필살기입니다.', '궁극기'),
  },
  {
    id: 'megumi-incomplete-domain',
    baseKey: 'megumi',
    variantName: '불완전한 영역',
    title: '식신 전개와 보조 화력을 함께 가져가는 범용 메구미',
    trait: 'shadow',
    combatType: 'cursed',
    role: 'support',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '한정',
    description: '식신을 활용한 안정적인 유틸과 광역 지원이 강한 메구미 변형입니다.',
    passive: '식신이 남아있는 동안 아군 전체의 속도와 명중 효율을 강화합니다.',
    skills: [
      skill('옥견 연계', '단일 적을 추격하며 아군 전체의 속도를 보조합니다.', '3턴'),
      skill('누에 전개', '적 전체에 술식 피해와 감전 계열 약화를 남깁니다.', '4턴'),
    ],
    ultimate: skill('불완전한 영역', '식신 다수를 동원해 전장 지배력을 높이는 필살기입니다.', '궁극기'),
  },
  {
    id: 'megumi-inherited-technique',
    baseKey: 'megumi',
    variantName: '계승된 술식',
    title: '정석적인 식신 운용과 안정감을 갖춘 기본형 SSR 메구미',
    trait: 'shadow',
    combatType: 'cursed',
    role: 'support',
    tier: 'A',
    rarity: 'SSR',
    releaseType: '일반',
    description: '식신 파티의 출발점이 되는 기본형 메구미 유닛입니다.',
    passive: '식신이 행동할 때마다 아군 전체에 작은 공격 보정을 나눠줍니다.',
    skills: [
      skill('식신 배치', '전열과 후열을 보조하는 버프를 제공합니다.', '2턴'),
      skill('그림자 묶기', '단일 적에게 이동 제어와 디버프를 부여합니다.', '3턴'),
    ],
    ultimate: skill('십종영법술', '여러 식신을 연속 호출해 광역 압박을 가합니다.', '궁극기'),
  },
  {
    id: 'megumi-bond',
    baseKey: 'megumi',
    variantName: '대의 인연',
    title: '아군 연계를 강화하는 편성형 메구미',
    trait: 'action',
    combatType: 'hybrid',
    role: 'support',
    tier: 'A',
    rarity: 'SSR',
    releaseType: '일반',
    description: '특정 조합에서 가치가 더 올라가는 연계형 메구미 카드입니다.',
    passive: '동일 특성 아군이 많을수록 식신 스택과 보조 성능이 상승합니다.',
    skills: [
      skill('연결된 그림자', '아군 한 명과 연동해 추가 효과를 부여합니다.', '3턴'),
      skill('후방 엄호', '아군의 받는 피해를 낮추고 추격 조건을 만듭니다.', '4턴'),
    ],
    ultimate: skill('묶인 인연', '아군 전체의 연계 화력을 키우는 지원형 필살기입니다.', '궁극기'),
  },
  {
    id: 'megumi-rabbit',
    baseKey: 'megumi',
    variantName: '토끼의 그림자',
    title: '속도와 회피 지원에 초점을 둔 기동형 메구미',
    trait: 'night',
    combatType: 'cursed',
    role: 'debuffer',
    tier: 'B',
    rarity: 'SSR',
    releaseType: '일반',
    description: '회피 보조와 적 교란에 강한 다목적 메구미 변형입니다.',
    passive: '회피 계열 버프가 걸리면 적의 명중과 치명 보정을 깎아냅니다.',
    skills: [
      skill('토끼 난무', '적 전체를 교란해 명중률을 떨어뜨립니다.', '2턴'),
      skill('그림자 도약', '자신과 아군의 기동성을 높입니다.', '3턴'),
    ],
    ultimate: skill('토끼 그림자 정원', '짧은 시간 적을 묶고 아군 회피를 강화하는 필살기입니다.', '궁극기'),
  },
  {
    id: 'nobara-steel',
    baseKey: 'nobara',
    variantName: '철골',
    title: '단일 고점이 높은 못 특화 디버프 어태커',
    trait: 'action',
    combatType: 'cursed',
    role: 'attacker',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '일반',
    description: '보스전에서 안정적인 단일 타점과 중첩 폭발을 보여주는 노바라 변형입니다.',
    passive: '못 중첩이 쌓일수록 대상이 받는 피해와 자신의 회심 효율이 상승합니다.',
    skills: [
      skill('추령주법', '단일 대상에 못 스택과 술식 피해를 부여합니다.', '2턴'),
      skill('공명 준비', '다음 공명 계열 피해를 크게 증폭시킵니다.', '3턴'),
    ],
    ultimate: skill('비녀 공명', '중첩된 못을 폭발시켜 큰 단일 피해를 가합니다.', '궁극기'),
  },
  {
    id: 'nobara-compatible-nails',
    baseKey: 'nobara',
    variantName: '상성이 좋은 못',
    title: '시너지를 받으면 더 강해지는 파티 의존형 노바라',
    trait: 'illusion',
    combatType: 'cursed',
    role: 'debuffer',
    tier: 'A',
    rarity: 'SSR',
    releaseType: '일반',
    description: '다른 디버퍼와 함께 쓸 때 피해 증폭 능력이 크게 올라가는 노바라 카드입니다.',
    passive: '디버프가 2개 이상 걸린 대상에게 추가 효과를 발동합니다.',
    skills: [
      skill('찌르기 준비', '적의 방어 관련 보정을 낮춥니다.', '2턴'),
      skill('상성 추적', '취약한 적에게 추가 피해를 부여합니다.', '3턴'),
    ],
    ultimate: skill('맞춤 공명', '약화가 누적된 적을 크게 터뜨리는 필살기입니다.', '궁극기'),
  },
  {
    id: 'nobara-drive-it-in',
    baseKey: 'nobara',
    variantName: '박아넣어',
    title: '짧은 사이클로 못 중첩을 빠르게 쌓는 공세형 노바라',
    trait: 'night',
    combatType: 'physical',
    role: 'breaker',
    tier: 'B',
    rarity: 'SSR',
    releaseType: '일반',
    description: '짧은 쿨다운과 빠른 템포가 장점인 기동형 노바라 변형입니다.',
    passive: '짧은 쿨다운 스킬을 돌릴수록 브레이크 압박과 추격 빈도가 올라갑니다.',
    skills: [
      skill('근거리 해머', '빠른 해머 타격으로 브레이크 수치를 깎습니다.', '2턴'),
      skill('연속 고정', '못 스택을 즉시 추가하며 다음 타격을 보조합니다.', '2턴'),
    ],
    ultimate: skill('박아넣어', '적 하나를 끝까지 밀어붙이는 연타형 필살기입니다.', '궁극기'),
  },
  {
    id: 'nanami-suppression',
    baseKey: 'nanami',
    variantName: '무언의 제압',
    title: '버프와 화력을 함께 가져가는 최상위 지원형 나나미',
    trait: 'night',
    combatType: 'hybrid',
    role: 'support',
    tier: 'SS',
    rarity: 'SSR',
    releaseType: '한정',
    description: '최신 보조 티어에서 상단에 보이는 나나미 변형으로, 전체 화력 버프가 매우 강력합니다.',
    passive: '자신이 행동할 때마다 아군 전체에 누적형 피해 버프를 분배합니다.',
    skills: [
      skill('제압의 시선', '적의 딜링 효율을 낮추고 아군 화력을 높입니다.', '3턴'),
      skill('침묵한 계산', '아군 전체의 회심과 피해량을 동시에 올립니다.', '4턴'),
    ],
    ultimate: skill('무언의 제압', '적 전체를 약화시키며 아군 전체의 마무리 화력을 극대화합니다.', '궁극기'),
  },
  {
    id: 'nanami-grade-one',
    baseKey: 'nanami',
    variantName: '1급 술사',
    title: '안정적인 딜링과 보조를 겸한 정석형 나나미',
    trait: 'action',
    combatType: 'hybrid',
    role: 'support',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '일반',
    description: '공격과 지원이 균형 잡힌 1급 술사 테마의 나나미 변형입니다.',
    passive: '약점을 맞출수록 아군 전체에 작은 공격 버프를 계속 쌓아줍니다.',
    skills: [
      skill('정밀 베기', '약점을 정확히 찔러 디버프를 남깁니다.', '2턴'),
      skill('업무 정리', '아군 전체의 템포를 안정적으로 보조합니다.', '3턴'),
    ],
    ultimate: skill('1급의 마무리', '단일 적과 주변 적을 함께 압박하는 필살기입니다.', '궁극기'),
  },
  {
    id: 'nanami-overtime',
    baseKey: 'nanami',
    variantName: '시간외 노동',
    title: '안정적인 체술 누적과 후반 고점이 특징인 1급 술사',
    trait: 'action',
    combatType: 'hybrid',
    role: 'attacker',
    tier: 'A',
    rarity: 'SSR',
    releaseType: '일반',
    description: '꾸준한 브레이크 압박과 후반 폭발력을 갖춘 나나미의 대표 공격형 카드입니다.',
    passive: '전투가 길어질수록 자신의 피해량과 치명 계수가 증가합니다.',
    skills: [
      skill('십획 베기', '약점을 정밀하게 찌르며 브레이크를 유도합니다.', '2턴'),
      skill('초과근무 선언', '다음 턴 동안 자신의 공격 템포를 끌어올립니다.', '3턴'),
    ],
    ultimate: skill('시간외 일격', '고배율 일격으로 단일 적을 압박하는 필살기입니다.', '궁극기'),
  },
  {
    id: 'nanami-ratio',
    baseKey: 'nanami',
    variantName: '십획주법',
    title: '브레이크와 확정 타점이 강한 기본형 체술 나나미',
    trait: 'shadow',
    combatType: 'physical',
    role: 'breaker',
    tier: 'A',
    rarity: 'SSR',
    releaseType: '일반',
    description: '단순한 조작으로 안정적인 브레이크 수치를 뽑는 나나미의 기본 변형입니다.',
    passive: '약점 판정이 발생할수록 추가 브레이크 수치를 획득합니다.',
    skills: [
      skill('분할 타격', '단일 적의 브레이크 게이지를 크게 깎습니다.', '2턴'),
      skill('정확도 상승', '다음 타격의 약점 판정률을 높입니다.', '3턴'),
    ],
    ultimate: skill('십획 마감', '약점 라인을 정교하게 꿰뚫는 단일 필살기입니다.', '궁극기'),
  },
  {
    id: 'yuta-executioner',
    baseKey: 'yuta',
    variantName: '사형 집행인',
    title: '고점 화력과 주력 회복이 모두 뛰어난 최신 최상위 유타',
    trait: 'shadow',
    combatType: 'hybrid',
    role: 'attacker',
    tier: 'SS',
    rarity: 'SSR',
    releaseType: '한정',
    description: '2026년 상반기 최강 공격형 표에서 빠지지 않는 대표 유타 변형입니다.',
    passive: '리카가 연동될수록 스킬 배율과 주력 회복이 동시에 강화됩니다.',
    skills: [
      skill('집행 준비', '자신의 계수와 회심 계열 수치를 높입니다.', '3턴'),
      skill('리카 참격', '광범위한 복합 피해를 가하고 다음 스킬을 강화합니다.', '4턴'),
    ],
    ultimate: skill('사형 집행', '리카와 함께 강한 처형 판정을 가하는 특급 필살기입니다.', '궁극기'),
  },
  {
    id: 'yuta-queen',
    baseKey: 'yuta',
    variantName: '여왕',
    title: '리카 연계로 공격과 보호를 함께 가져가는 최상위 특급 유닛',
    trait: 'shadow',
    combatType: 'hybrid',
    role: 'support',
    tier: 'SS',
    rarity: 'SSR',
    releaseType: '한정',
    description: '리세마라 가치와 장기 운용 가치가 모두 높은 올라운더 유타 변형입니다.',
    passive: '리카가 동행 중일 때 아군 보호막과 자신의 스킬 위력이 함께 상승합니다.',
    skills: [
      skill('리카의 참격', '적을 절단하며 동시에 아군 전체의 피해 저항을 강화합니다.', '3턴'),
      skill('반전 지원', '체력이 낮은 아군을 우선 보조하고 디버프를 완화합니다.', '4턴'),
    ],
    ultimate: skill('사랑의 특급 주력', '광역 공격 뒤 아군을 회복하며 리카 연계를 강화합니다.', '궁극기'),
  },
  {
    id: 'yuta-lend-me-your-power',
    baseKey: 'yuta',
    variantName: '힘을 빌려줘',
    title: '회복과 보조 딜을 겸한 안정형 유타',
    trait: 'action',
    combatType: 'hybrid',
    role: 'healer',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '일반',
    description: '장기전에서 안정적인 회복과 보조 타격을 맡는 유타 변형입니다.',
    passive: '아군 체력이 낮아질수록 치유량과 보호량이 상승합니다.',
    skills: [
      skill('리카의 가호', '아군 전체에게 보호막과 회복을 제공합니다.', '3턴'),
      skill('반전술식', '단일 아군을 강하게 치유하고 약화를 일부 해제합니다.', '3턴'),
    ],
    ultimate: skill('빌려온 힘', '아군 전체의 전열을 다시 세우는 회복형 필살기입니다.', '궁극기'),
  },
  {
    id: 'toji-sorcerer-killer',
    baseKey: 'toji',
    variantName: '술사 살해자',
    title: '고배율 체술과 무주력 연계가 강한 단일 브레이커',
    trait: 'illusion',
    combatType: 'physical',
    role: 'breaker',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '한정',
    description: '고난도 보스전에서 높은 타점과 브레이크 압박을 보여주는 토우지의 대표 변형입니다.',
    passive: '주력 소비 없이 행동할수록 체술 배율과 브레이크 효율이 상승합니다.',
    skills: [
      skill('천역모 일격', '방어를 무시하며 강한 단일 체술 피해를 가합니다.', '2턴'),
      skill('흔적 없는 침투', '행동 게이지를 회복하고 다음 타격을 강화합니다.', '3턴'),
    ],
    ultimate: skill('특급 사냥', '단일 적을 확실히 마무리하는 고배율 필살기입니다.', '궁극기'),
  },
  {
    id: 'toji-incarnation',
    baseKey: 'toji',
    variantName: '강령',
    title: '폭발적인 첫 턴 화력에 특화된 강림형 토우지',
    trait: 'night',
    combatType: 'physical',
    role: 'attacker',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '한정',
    description: '등장 직후부터 높은 타점을 뽑는 강령 토우지 계열의 핵심 카드입니다.',
    passive: '첫 진입 턴의 체술 피해와 회심 피해가 크게 상승합니다.',
    skills: [
      skill('강림 베기', '진입 직후 강한 단일 피해를 가합니다.', '2턴'),
      skill('살의 증폭', '자신의 회심과 속도를 끌어올립니다.', '3턴'),
    ],
    ultimate: skill('강령 살법', '등장한 순간의 기세를 그대로 꽂아 넣는 필살기입니다.', '궁극기'),
  },
  {
    id: 'mahito-soul',
    baseKey: 'mahito',
    variantName: '영혼',
    title: '환 특성 디버프 메타를 여는 광역 약화 핵심 유닛',
    trait: 'illusion',
    combatType: 'hybrid',
    role: 'debuffer',
    tier: 'SS',
    rarity: 'SSR',
    releaseType: '한정',
    description: '환 특성 파티의 중심축으로 불릴 만큼 강한 피해 증가 디버프를 갖춘 마히토입니다.',
    passive: '적에게 걸린 약화 효과 수만큼 자신의 피해와 디버프 적중률이 상승합니다.',
    skills: [
      skill('무위전변', '적 전체에 약화 중첩을 남기고 피해를 증폭시킵니다.', '3턴'),
      skill('영혼 침식', '단일 적의 영혼을 깎아 추가 피해 조건을 만듭니다.', '3턴'),
    ],
    ultimate: skill('영혼 파형', '광역 디버프와 폭발 피해를 함께 넣는 마히토의 필살기입니다.', '궁극기'),
  },
  {
    id: 'mahito-death',
    baseKey: 'mahito',
    variantName: '죽음의 영감',
    title: '지속 피해와 교란에 무게를 둔 환 특성 마히토',
    trait: 'illusion',
    combatType: 'cursed',
    role: 'debuffer',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '일반',
    description: '지속 피해와 상태이상 교란에 강한 전통적인 마히토 변형입니다.',
    passive: '적이 상태이상에 걸릴 때마다 자신의 술식 위력과 지속 피해량이 상승합니다.',
    skills: [
      skill('죽음의 속삭임', '적 전체에 지속 피해를 남깁니다.', '3턴'),
      skill('영혼 흔들기', '단일 적의 상태이상 지속 시간을 늘립니다.', '3턴'),
    ],
    ultimate: skill('죽음의 영감', '지속 피해를 한 번에 터뜨리는 필살기입니다.', '궁극기'),
  },
  {
    id: 'sukuna-fuga',
    baseKey: 'sukuna',
    variantName: '후가',
    title: '현 메타 상위권 광역 마무리와 지속 압박을 가진 저주의 왕',
    trait: 'shadow',
    combatType: 'cursed',
    role: 'attacker',
    tier: 'SS',
    rarity: 'SSR',
    releaseType: '한정',
    description: '최신 최강 캐릭터 표에서 꾸준히 상단을 차지하는 숙나 변형입니다.',
    passive: '영역 전개 계열 스킬 사용 뒤 술식 위력을 누적시키고, 적의 지속 피해를 강화합니다.',
    skills: [
      skill('해', '적을 절단하며 열상 효과를 부여합니다.', '2턴'),
      skill('화염 개방', '전방 범위를 태워 광역 술식 피해를 가합니다.', '4턴'),
    ],
    ultimate: skill('후가', '거대한 화염으로 전장을 태우는 숙나의 결정타 필살기입니다.', '궁극기'),
  },
  {
    id: 'sukuna-true-jujutsu',
    baseKey: 'sukuna',
    variantName: '본물의 주술',
    title: '영역 전개와 열상 누적에 특화된 기본형 숙나 SSR',
    trait: 'shadow',
    combatType: 'cursed',
    role: 'attacker',
    tier: 'S',
    rarity: 'SSR',
    releaseType: '한정',
    description: '열상 누적과 광역 필살기 성능 때문에 여전히 높은 순위로 묶이는 숙나 카드입니다.',
    passive: '적에게 열상을 여러 번 부여할수록 자신의 필살기 위력이 상승합니다.',
    skills: [
      skill('주술의 절단', '단일 적에게 열상을 누적시킵니다.', '2턴'),
      skill('영역 준비', '필살기 게이지와 술식 계수를 동시에 올립니다.', '4턴'),
    ],
    ultimate: skill('복마어주자', '영역 전개와 함께 광역 열상을 부여하는 필살기입니다.', '궁극기'),
  },
  {
    id: 'maki-rebellious',
    baseKey: 'maki',
    variantName: '반골',
    title: '무주력 피지컬을 살린 초중반 전투형 어태커',
    trait: 'illusion',
    combatType: 'physical',
    role: 'attacker',
    tier: 'B',
    rarity: 'SSR',
    releaseType: '일반',
    description: '자원 부담이 적고 단순한 운영이 가능한 마키 변형으로, 초반 전개에서 쓰기 편합니다.',
    passive: '주력 소모 없이 공격할수록 다음 턴의 체술 위력이 상승합니다.',
    skills: [
      skill('장병기 강타', '전방 대상에게 묵직한 물리 피해를 줍니다.', '2턴'),
      skill('거리 압박', '적의 체술 저항을 깎고 자신에게 방어 보정을 부여합니다.', '3턴'),
    ],
    ultimate: skill('반골의 전력 베기', '중거리에서 강한 일격을 날리는 체술 필살기입니다.', '궁극기'),
  },
  {
    id: 'maki-greatblade',
    baseKey: 'maki',
    variantName: '대도',
    title: '전열을 밀어붙이는 무기 특화형 마키',
    trait: 'night',
    combatType: 'physical',
    role: 'breaker',
    tier: 'B',
    rarity: 'SSR',
    releaseType: '일반',
    description: '거대한 무기 한 방으로 브레이크를 노리는 마키 변형입니다.',
    passive: '중무기 계열 스킬 사용 시 적의 브레이크 저항을 낮춥니다.',
    skills: [
      skill('중무기 휘두르기', '단일 적의 브레이크 수치를 크게 깎습니다.', '2턴'),
      skill('압박 돌진', '전방으로 파고들며 추가 행동 조건을 만듭니다.', '3턴'),
    ],
    ultimate: skill('대도의 낙하', '무기 무게를 실어 브레이크와 피해를 동시에 넣는 필살기입니다.', '궁극기'),
  },
  {
    id: 'maki-early-morning',
    baseKey: 'maki',
    variantName: '이른 아침 수행',
    title: '기초 스탯과 생존에 초점을 둔 밸런스형 마키',
    trait: 'action',
    combatType: 'physical',
    role: 'defender',
    tier: 'C',
    rarity: 'SSR',
    releaseType: '일반',
    description: '공격보다는 안정적인 버티기와 중간 역할 수행에 가까운 마키 유닛입니다.',
    passive: '턴이 지날수록 방어와 반격 계수가 차분히 상승합니다.',
    skills: [
      skill('아침 루틴', '자신의 방어와 속도를 보강합니다.', '2턴'),
      skill('훈련 반격', '맞은 뒤 바로 반격할 수 있는 상태를 만듭니다.', '3턴'),
    ],
    ultimate: skill('성실한 일격', '안정적인 반격 운영을 돕는 필살기입니다.', '궁극기'),
  },
  {
    id: 'toge-determination',
    baseKey: 'toge',
    variantName: '각오',
    title: '상태 제어와 보조를 동시에 수행하는 주언형 서포터',
    trait: 'action',
    combatType: 'cursed',
    role: 'support',
    tier: 'B',
    rarity: 'SSR',
    releaseType: '일반',
    description: '행동 불가와 아군 보조를 함께 담당하는 토게의 표준적인 SSR 변형입니다.',
    passive: '상태이상에 걸린 적이 있으면 아군 전체의 술식 효율이 증가합니다.',
    skills: [
      skill('멈춰', '단일 적의 행동을 봉쇄합니다.', '3턴'),
      skill('도망쳐', '아군에게 생존 보조 버프를 부여합니다.', '4턴'),
    ],
    ultimate: skill('부서져라', '전체 적을 밀어내며 상태이상 확률을 끌어올리는 필살기입니다.', '궁극기'),
  },
  {
    id: 'toge-crush',
    baseKey: 'toge',
    variantName: '부서져라',
    title: '광역 제어 비중이 더 높은 공격적인 주언 변형',
    trait: 'illusion',
    combatType: 'cursed',
    role: 'debuffer',
    tier: 'B',
    rarity: 'SSR',
    releaseType: '일반',
    description: '광역으로 적 템포를 무너뜨리는 데 강한 토게 카드입니다.',
    passive: '적을 묶을수록 디버프 적중률과 광역 피해가 오릅니다.',
    skills: [
      skill('찌그러져라', '적 전체에 약한 구속과 피해를 겁니다.', '3턴'),
      skill('멈춤의 파동', '행동 게이지를 늦추고 약화를 겹칩니다.', '3턴'),
    ],
    ultimate: skill('압살 주언', '광역 억제력에 초점을 둔 필살기입니다.', '궁극기'),
  },
  {
    id: 'toge-night-walk',
    baseKey: 'toge',
    variantName: '밤을 걷는 주언',
    title: '회피와 교란을 섞은 기동형 토게',
    trait: 'night',
    combatType: 'cursed',
    role: 'support',
    tier: 'C',
    rarity: 'SSR',
    releaseType: '일반',
    description: '직접 화력보다 회피와 교란을 돕는 가벼운 토게 변형입니다.',
    passive: '야 특성 아군이 많을수록 회피와 명중 교란량이 증가합니다.',
    skills: [
      skill('속삭이는 주언', '적의 정확도를 낮추고 아군 회피를 보조합니다.', '2턴'),
      skill('야간 교란', '상대의 턴 계획을 흐트러뜨립니다.', '3턴'),
    ],
    ultimate: skill('야행의 말', '짧게 흐름을 끊는 보조형 필살기입니다.', '궁극기'),
  },
  {
    id: 'panda-mutant-corpse',
    baseKey: 'panda',
    variantName: '변이 주해',
    title: '도발과 반격으로 파티 전열을 지켜주는 안정형 방어 카드',
    trait: 'night',
    combatType: 'physical',
    role: 'defender',
    tier: 'C',
    rarity: 'SSR',
    releaseType: '일반',
    description: '초반 탱킹과 반격 운영을 담당하는 판다 변형으로, 버티는 전투에서 장점이 있습니다.',
    passive: '피격 횟수에 따라 반격률과 방어 계수가 누적 상승합니다.',
    skills: [
      skill('판다 펀치', '전방 적을 밀어내며 도발을 유도합니다.', '2턴'),
      skill('수비 전환', '자신에게 방어 버프와 약한 회복 효과를 부여합니다.', '3턴'),
    ],
    ultimate: skill('고릴라 모드', '탱킹과 반격을 동시에 강화하는 판다의 필살기입니다.', '궁극기'),
  },
  {
    id: 'panda-helping-hand',
    baseKey: 'panda',
    variantName: '도와줄게',
    title: '전열 보호와 약한 회복을 섞은 서브 탱커형 판다',
    trait: 'action',
    combatType: 'physical',
    role: 'defender',
    tier: 'C',
    rarity: 'SSR',
    releaseType: '일반',
    description: '보호와 회복을 함께 챙기는 서브 탱커형 판다 유닛입니다.',
    passive: '아군 체력이 낮아질수록 대신 받아주는 피해량과 보호 효율이 상승합니다.',
    skills: [
      skill('앞으로 나와', '적의 시선을 자신에게 끌고 짧은 보호막을 생성합니다.', '2턴'),
      skill('뒤는 맡겨', '아군 전체의 받는 피해를 완화합니다.', '3턴'),
    ],
    ultimate: skill('먼저 막아설게', '짧은 시간 팀 전체의 안정성을 끌어올리는 필살기입니다.', '궁극기'),
  },
];

export const mockCharacterDetails: CharacterDetail[] = characterSeeds.map(createCharacter);

export const mockCharacters: CharacterSummary[] = mockCharacterDetails.map(
  ({ description: _description, passive: _passive, skills: _skills, ultimate: _ultimate, ...summary }) => summary,
);

const tierHeadlines: Record<CharacterDetail['tier'], string> = {
  SS: '최신 리세마라와 메타 상위권에서 최우선으로 거론되는 변형 유닛.',
  S: '리세마라 상위권이거나 장기 운용 가치가 높은 우수한 핵심 카드.',
  A: '안정적으로 기용하기 좋은 범용 실전 카드.',
  B: '상황과 편성에 따라 채용 가치가 올라가는 보조 카드.',
  C: '초반 운영이나 특정 기믹 대응에 적합한 카드.',
};

export const mockTiers: TierGroup[] = tierOrder.map((tier) => ({
  tier,
  headline: tierHeadlines[tier],
  characterIds: mockCharacterDetails
    .filter((character) => character.tier === tier)
    .map((character) => character.id),
}));
